"""initial_schema

Revision ID: 7e3d55803069
Revises: 
Create Date: 2026-07-01 08:15:45.253278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3d55803069'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_passed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_discriminativeness',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('info_gain', sa.Float(), nullable=False),
    sa.Column('normalized_ig', sa.Float(), nullable=False),
    sa.Column('variance_score', sa.Float(), nullable=False),
    sa.Column('per_group_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('group_cohesivity',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('cohesivity', sa.Float(), nullable=False),
    sa.Column('per_category', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_embedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('categories_key', sa.String(length=50), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'category_id', 'categories_key')
    )
    op.create_table('group_group_similarity',
    sa.Column('group_a_id', sa.Integer(), nullable=False),
    sa.Column('group_b_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('per_category', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_a_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['group_b_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_a_id', 'group_b_id')
    )
    op.create_table('question_category',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'category_id')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('commission_id', sa.Integer(), nullable=True),
    sa.Column('circonscription', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'question_id')
    )
    op.create_table('voter_embedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('categories_key', sa.String(length=50), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id', 'category_id', 'categories_key')
    )
    op.create_table('voter_group_similarity',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('shared_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('per_category', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'group_id')
    )
    op.create_table('voter_voter_similarity',
    sa.Column('voter_a_id', sa.Integer(), nullable=False),
    sa.Column('voter_b_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('raw_similarity', sa.Float(), nullable=False),
    sa.Column('shared_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('per_category', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['voter_a_id'], ['voters.id'], ),
    sa.ForeignKeyConstraint(['voter_b_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('voter_a_id', 'voter_b_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voter_voter_similarity')
    op.drop_table('voter_group_similarity')
    op.drop_table('voter_embedding')
    op.drop_table('answers')
    op.drop_table('voters')
    op.drop_table('question_category')
    op.drop_table('group_group_similarity')
    op.drop_table('group_embedding')
    op.drop_table('group_cohesivity')
    op.drop_table('category_discriminativeness')
    op.drop_table('roles')
    op.drop_table('questions')
    op.drop_table('groups')
    op.drop_table('commissions')
    op.drop_table('categories')
    # ### end Alembic commands ###
