"""add per_category to person_person_similarity

Revision ID: 98847eb27900
Revises: c74e546ec80d
Create Date: 2026-06-23 14:29:13.535793

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98847eb27900'
down_revision: str | None = 'c74e546ec80d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_person_similarity', sa.Column('per_category', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_person_similarity', 'per_category')
    # ### end Alembic commands ###
