"""initial schema

Revision ID: c74e546ec80d
Revises: 
Create Date: 2026-06-22 11:19:46.647500

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c74e546ec80d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('group_cohesivity',
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('cohesivity', sa.Float(), nullable=False),
                    sa.Column('per_category', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.PrimaryKeyConstraint('group_id')
                    )
    op.create_table('group_group_similarity',
                    sa.Column('group_a_id', sa.Integer(), nullable=False),
                    sa.Column('group_b_id', sa.Integer(), nullable=False),
                    sa.Column('similarity', sa.Float(), nullable=False),
                    sa.Column('per_category', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['group_a_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['group_b_id'], ['groups.id'], ),
                    sa.PrimaryKeyConstraint('group_a_id', 'group_b_id')
                    )
    op.create_table('people',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('question_category',
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                    sa.PrimaryKeyConstraint('question_id', 'category_id')
                    )
    op.create_table('answers',
                    sa.Column('person_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Boolean(), nullable=False),
                    sa.Column('answered_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                    sa.PrimaryKeyConstraint('person_id', 'question_id')
                    )
    op.create_table('person_group_similarity',
                    sa.Column('person_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('similarity', sa.Float(), nullable=False),
                    sa.Column('shared_count', sa.Integer(), nullable=False),
                    sa.Column('confidence', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
                    sa.PrimaryKeyConstraint('person_id', 'group_id')
                    )
    op.create_table('person_person_similarity',
                    sa.Column('person_a_id', sa.Integer(), nullable=False),
                    sa.Column('person_b_id', sa.Integer(), nullable=False),
                    sa.Column('similarity', sa.Float(), nullable=False),
                    sa.Column('raw_similarity', sa.Float(), nullable=False),
                    sa.Column('shared_count', sa.Integer(), nullable=False),
                    sa.Column('confidence', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['person_a_id'], ['people.id'], ),
                    sa.ForeignKeyConstraint(['person_b_id'], ['people.id'], ),
                    sa.PrimaryKeyConstraint('person_a_id', 'person_b_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_person_similarity')
    op.drop_table('person_group_similarity')
    op.drop_table('answers')
    op.drop_table('question_category')
    op.drop_table('people')
    op.drop_table('group_group_similarity')
    op.drop_table('group_cohesivity')
    op.drop_table('questions')
    op.drop_table('groups')
    op.drop_table('categories')
    # ### end Alembic commands ###
