"""add per_category to person_group_similarity

Revision ID: e41a6efd589b
Revises: 1d9941e43959
Create Date: 2026-06-23 15:11:08.761739

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e41a6efd589b'
down_revision: str | None = '1d9941e43959'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_group_similarity', sa.Column('per_category', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_group_similarity', 'per_category')
    # ### end Alembic commands ###
